root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -tags sqlite_fts5 -o ./tmp/main ."
entrypoint = "./tmp/main"
args_bin = ["run"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test.go"]
delay = 1000
stop_watch = ["tmp/"]

[log]
time = true

[misc]
clean_on_exit = true
