// Generated by tool/generate_branding.py from assets/branding/moneef-icon.svg.
// Paints immediately on the first frame, with no asset decode or font dependency.
import 'package:flutter/material.dart';

class MoneefLogo extends StatelessWidget {
  const MoneefLogo({super.key, this.size = 96});
  final double size;

  @override
  Widget build(BuildContext context) => SizedBox.square(
    dimension: size,
    child: CustomPaint(painter: _FoldMPainter()),
  );
}

class _FoldMPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.save();
    canvas.scale(size.width / 100, size.height / 100);
    canvas.drawRRect(
      RRect.fromRectAndRadius(const Rect.fromLTWH(0, 0, 100, 100), const Radius.circular(24)),
      Paint()..color = const Color(0xFF6C5CE7),
    );
    canvas.translate(11, 11);
    canvas.scale(1.21875);
    canvas.drawPath(
      Path()
      ..moveTo(10, 49)
      ..lineTo(10, 15)
      ..lineTo(19, 15)
      ..lineTo(32, 30)
      ..lineTo(45, 15)
      ..lineTo(54, 15)
      ..lineTo(54, 49)
      ..lineTo(43, 49)
      ..lineTo(43, 32)
      ..lineTo(32, 44)
      ..lineTo(21, 32)
      ..lineTo(21, 49)
      ..close(),
      Paint()..color = const Color(0xFFFFFFFF).withValues(alpha: 1),
    );
    canvas.drawPath(
      Path()
      ..moveTo(19, 15)
      ..lineTo(32, 30)
      ..lineTo(24, 39)
      ..lineTo(19, 33)
      ..close(),
      Paint()..color = const Color(0xFF6C5CE7).withValues(alpha: 0.22),
    );
    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant _FoldMPainter oldDelegate) => false;
}
