#!/usr/bin/env python3
"""Generate Flutter and Android branding from the approved Fold M SVG.

Run: python3 tool/generate_branding.py [--check]
Requires rsvg-convert (librsvg) for PNGs. No network access is used.
"""

import argparse
from pathlib import Path
import re
import subprocess
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
RES = Path('android/app/src/main/res')
SOURCE = ROOT / 'assets/branding/moneef-icon.svg'
NS = {'svg': 'http://www.w3.org/2000/svg'}
svg = ET.parse(SOURCE).getroot()
rect = svg.find('svg:rect', NS)
group = svg.find('svg:g', NS)
paths = group.findall('svg:path', NS)
color = rect.attrib['fill']
radius = float(rect.attrib['rx'])
tx, ty, scale = map(float, re.fullmatch(
    r'translate\(([\d.]+) ([\d.]+)\) scale\(([\d.]+)\)',
    group.attrib['transform'],
).groups())
outputs = {}


def add(path, contents):
    outputs[Path(path)] = contents.encode() if isinstance(contents, str) else contents


def vector(size, viewport, content):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp" android:height="{size}dp"
    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">
{content}
</vector>
'''


def native_paths(monochrome=False):
    return '\n'.join(
        f'        <path android:fillColor="{p.attrib["fill"]}" '
        f'android:fillAlpha="{p.get("opacity", "1")}" '
        f'android:pathData="{p.attrib["d"]}" />'
        for p in (paths[:1] if monochrome else paths)
    )


def native_mark(monochrome=False):
    return f'''    <group android:translateX="{tx}" android:translateY="{ty}"
        android:scaleX="{scale}" android:scaleY="{scale}">
{native_paths(monochrome)}
    </group>'''


r = radius
# Cubic quarter circles match SVG rect rounding, unlike quadratic corners.
k = r * (1 - 0.5522847498)
rounded = (f'M{r},0 H{100-r} C{100-k},0 100,{k} 100,{r} V{100-r} '
           f'C100,{100-k} {100-k},100 {100-r},100 H{r} '
           f'C{k},100 0,{100-k} 0,{100-r} V{r} C0,{k} {k},0 {r},0 Z')
icon = f'    <path android:fillColor="{color}" android:pathData="{rounded}" />\n{native_mark()}'
add(RES / 'drawable/moneef_logo.xml', vector(96, 100, icon))
# Android 12 renders a 288dp icon area. The artwork occupies its central 96dp.
add(RES / 'drawable/moneef_splash.xml', vector(288, 300,
    f'    <group android:translateX="100" android:translateY="100">\n{icon}\n    </group>'))
for name, mono in [('ic_launcher_foreground', False), ('ic_launcher_monochrome', True)]:
    # Map the 100-unit preview into Android's central 72/108dp adaptive area.
    add(RES / f'drawable/{name}.xml', vector(108, 108,
        f'    <group android:translateX="18" android:translateY="18" android:scaleX="0.72" android:scaleY="0.72">\n{native_mark(mono)}\n    </group>'))
for version in [26, 33]:
    monochrome = '\n    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />' if version >= 33 else ''
    add(RES / f'mipmap-anydpi-v{version}/ic_launcher.xml', f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.py. The launcher chooses the mask. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/moneef_violet" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />{monochrome}
</adaptive-icon>
''')
add(RES / 'values/brand_colors.xml', f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.py. -->
<resources>
    <color name="moneef_violet">{color}</color>
</resources>
''')
for density, size in [('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)]:
    add(RES / f'mipmap-{density}/ic_launcher.png', subprocess.check_output(
        ['rsvg-convert', '-w', str(size), '-h', str(size), str(SOURCE)]))
add('assets/branding/moneef-icon.png', subprocess.check_output(
    ['rsvg-convert', '-w', '1024', '-h', '1024', str(SOURCE)]))


def dart_path(data):
    """Translate this logo's straight-line SVG commands into a Flutter Path."""
    tokens = re.findall(r'[A-Za-z]|-?\d+(?:\.\d+)?', data)
    result = ['Path()']
    i, x, y = 0, 0., 0.
    command = None
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
        absolute = command.isupper()
        op = command.upper()
        if op == 'Z':
            result.append('..close()')
            continue
        if op not in ('M', 'L', 'H', 'V'):
            raise ValueError(f'Unsupported logo command: {command}')
        value = float(tokens[i])
        i += 1
        if op in ('M', 'L'):
            yval = float(tokens[i])
            i += 1
            x = value if absolute else x + value
            y = yval if absolute else y + yval
        elif op == 'H':
            x = value if absolute else x + value
        else:
            y = value if absolute else y + value
        result.append(f'..{"moveTo" if op == "M" else "lineTo"}({x:g}, {y:g})')
        if op == 'M':
            command = 'L' if absolute else 'l'
    return '\n      '.join(result)


paint_paths = '\n'.join(
    f'''    canvas.drawPath(
      {dart_path(p.attrib['d'])},
      Paint()..color = const Color(0xFF{p.attrib['fill'][1:]}).withValues(alpha: {p.get('opacity', '1')}),
    );'''
    for p in paths
)
add('lib/widgets/branding/moneef_logo.dart', f'''// Generated by tool/generate_branding.py from assets/branding/moneef-icon.svg.
// Paints immediately on the first frame, with no asset decode or font dependency.
import 'package:flutter/material.dart';

class MoneefLogo extends StatelessWidget {{
  const MoneefLogo({{super.key, this.size = 96}});
  final double size;

  @override
  Widget build(BuildContext context) => SizedBox.square(
    dimension: size,
    child: CustomPaint(painter: _FoldMPainter()),
  );
}}

class _FoldMPainter extends CustomPainter {{
  @override
  void paint(Canvas canvas, Size size) {{
    canvas.save();
    canvas.scale(size.width / 100, size.height / 100);
    canvas.drawRRect(
      RRect.fromRectAndRadius(const Rect.fromLTWH(0, 0, 100, 100), const Radius.circular({radius:g})),
      Paint()..color = const Color(0xFF{color[1:]}),
    );
    canvas.translate({tx:g}, {ty:g});
    canvas.scale({scale});
{paint_paths}
    canvas.restore();
  }}

  @override
  bool shouldRepaint(covariant _FoldMPainter oldDelegate) => false;
}}
''')

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Report stale generated files without writing.')
args = parser.parse_args()
stale = []
for relative, contents in outputs.items():
    destination = ROOT / relative
    if destination.exists() and destination.read_bytes() == contents:
        continue
    stale.append(str(relative))
    if not args.check:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(contents)
if args.check and stale:
    raise SystemExit('Stale branding files:\n' + '\n'.join(stale))
print(f'{len(outputs)} branding files {"verified" if args.check else "generated"}.')
